# Generated by Django 6.0.3 on 2026-03-30 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ECG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=255)),
                ('exam_date', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='ecg/')),
                ('result', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
