# Generated by Django 6.0.3 on 2026-05-08 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecg', '0002_ecg_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardioFluxAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=255)),
                ('exam_date', models.DateTimeField()),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('classification', models.CharField(blank=True, max_length=255, null=True)),
                ('st_status', models.CharField(blank=True, max_length=100, null=True)),
                ('st_elevation', models.FloatField(blank=True, null=True)),
                ('sd1', models.FloatField(blank=True, null=True)),
                ('sd2', models.FloatField(blank=True, null=True)),
                ('ratio', models.FloatField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('result', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
